**This notebook is an exercise in the [SQL](https://www.kaggle.com/learn/intro-to-sql) course.  You can reference the tutorial at [this link](https://www.kaggle.com/dansbecker/getting-started-with-sql-and-bigquery).**

---

# Introduction

The first test of your new data exploration skills uses data describing crime in the city of Chicago.

Before you get started, run the following cell. It sets up the automated feedback system to review your answers.

In [1]:
# Set up feedack system
from learntools.core import binder
binder.bind(globals())
from learntools.sql.ex1 import *
print("Setup Complete")

/usr/local/lib/python3.11/dist-packages/learntools/sql/ex1.py:64: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (type(fields_for_plotting[0] == str), "The first item in `fields_for_plotting` should be a string.")
/usr/local/lib/python3.11/dist-packages/learntools/sql/ex1.py:65: SyntaxWarning: assertion is always true, perhaps remove parentheses?
  assert (type(fields_for_plotting[1] == str), "The second item in `fields_for_plotting` should be a string.")

Using Kaggle's public dataset BigQuery integration.
Setup Complete

Use the next code cell to fetch the dataset.

In [2]:
from google.cloud import bigquery

# Create a "Client" object
client = bigquery.Client()

# Construct a reference to the "chicago_crime" dataset
dataset_ref = client.dataset("chicago_crime", project="bigquery-public-data")

# API request - fetch the dataset
dataset = client.get_dataset(dataset_ref)

Using Kaggle's public dataset BigQuery integration.

# Exercises

### 1) Count tables in the dataset

How many tables are in the Chicago Crime dataset?

In [3]:
# Write the code you need here to figure out the answer
tables = list(client.list_tables(dataset))

# Print names of all tables in the dataset (there are four!)
for table in tables:  
    print(table.table_id)

# Print the len of tables
num_tables = len(tables)
print(num_tables)

crime
1

In [4]:
#num_tables = ____  # Store the answer as num_tables and then run this cell

# Check your answer
q_1.check()

Correct

For a hint or the solution, uncomment the appropriate line below.

In [5]:
#q_1.hint()
#q_1.solution()

### 2) Explore the table schema

How many columns in the `crime` table have `TIMESTAMP` data?

In [6]:
# Write the code to figure out the answer

# Construct a reference to the "full" table
table_ref = dataset_ref.table("crime")

# API request - fetch the table
table = client.get_table(table_ref)


timestamp_fields = [i for i in table.schema if i.field_type=='TIMESTAMP']
num_timestamp_fields = len(timestamp_fields)

In [7]:
#num_timestamp_fields = ____ # Put your answer here

# Check your answer
q_2.check()

Correct

For a hint or the solution, uncomment the appropriate line below.

In [8]:
#q_2.hint()
#q_2.solution()

### 3) Create a crime map

If you wanted to create a map with a dot at the location of each crime, what are the names of the two fields you likely need to pull out of the `crime` table to plot the crimes on a map?

In [9]:
# Write the code here to explore the data so you can find the answer


# Map the schema list into a dictionary
schema_dict = {field.name: field for field in table.schema}

[print(i) for i in schema_dict]

#field_x = schema_dict.get('x_coordinate')
#field_y = schema_dict.get('y_coordinate')

unique_key
case_number
date
block
iucr
primary_type
description
location_description
arrest
domestic
beat
district
ward
community_area
fbi_code
x_coordinate
y_coordinate
year
updated_on
latitude
longitude
location

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [10]:
fields_for_plotting = ['latitude', 'longitude'] # Put your answers here

# Check your answer
q_3.check()

Correct

For a hint or the solution, uncomment the appropriate line below.

In [11]:
#q_3.hint()
#q_3.solution()

Thinking about the question above, there are a few columns that appear to have geographic data. Look at a few values (with the `list_rows()` command) to see if you can determine their relationship.  Two columns will still be hard to interpret. But it should be obvious how the `location` column relates to `latitude` and `longitude`.

In [12]:
# Scratch space for your code

client.list_rows(table, max_results=5).to_dataframe()

,unique_key,case_number,date,block,iucr,primary_type,description,location_description,arrest,domestic,...,ward,community_area,fbi_code,x_coordinate,y_coordinate,year,updated_on,latitude,longitude,location
0,10966486,JA289203,2017-05-28 17:30:00+00:00,001XX N WABASH AVE,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,CTA PLATFORM,False,False,...,42,32,02,1176791.0,1901351.0,2017,2018-02-10 15:50:01+00:00,41.884654,-87.626252,"(41.884653752, -87.626251847)"
1,9797811,HX446989,2014-09-25 01:00:00+00:00,0000X E LAKE ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,RESIDENCE,False,False,...,42,32,02,1176981.0,1901745.0,2014,2018-02-10 15:50:01+00:00,41.885731,-87.625542,"(41.885730611, -87.625542215)"
2,6276393,HP363165,2008-05-29 13:58:00+00:00,001XX S WACKER DR,031A,ROBBERY,ARMED: HANDGUN,BANK,True,False,...,2,32,03,1173889.0,1899510.0,2008,2018-02-28 15:56:25+00:00,41.879667,-87.636963,"(41.879667054, -87.63696315)"
3,11737450,JC322899,2019-06-26 14:10:00+00:00,001XX N MICHIGAN AVE,031A,ROBBERY,ARMED: HANDGUN,BANK,True,False,...,42,32,03,1177270.0,1901551.0,2019,2019-07-16 15:40:47+00:00,41.885192,-87.624487,"(41.885191719, -87.624486846)"
4,10795915,HZ566634,2016-12-27 14:15:00+00:00,003XX N MICHIGAN AVE,0320,ROBBERY,STRONGARM - NO WEAPON,SIDEWALK,False,False,...,42,32,03,1177244.0,1902417.0,2016,2018-02-10 15:50:01+00:00,41.887569,-87.624556,"(41.887568658, -87.624556055)"

In [13]:
!pip install --upgrade google-cloud-bigquery-storage pyarrow

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7dfbc6695fd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/google-cloud-bigquery-storage/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7dfbc6659850>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/google-cloud-bigquery-storage/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7dfbc6793ad0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/google-cloud-bigquery-storage/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7dfbc66ab110>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/google-cloud-bigquery-storage/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x7dfbc6692490>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/google-cloud-bigquery-storage/
ERROR: Could not find a version that satisfies the requirement google-cloud-bigquery-storage (from versions: none)
ERROR: No matching distribution found for google-cloud-bigquery-storage

In [14]:
#fields_to_get = [field for field in table.schema if field.name in ["x_coordinate", "y_coordinate", "location"]]

# Fetch rows with selected_fields applied
#rows = client.list_rows(table, selected_fields=fields_to_get, max_results=5)
#df = rows.to_dataframe()


query = """
    SELECT x_coordinate, y_coordinate, latitude, longitude
    FROM `bigquery-public-data.chicago_crime.crime`
    TABLESAMPLE SYSTEM (0.5 PERCENT)
    WHERE x_coordinate IS NOT NULL AND y_coordinate IS NOT NULL
"""


df = client.query(query).to_dataframe()

df.describe()

/usr/local/lib/python3.11/dist-packages/google/cloud/bigquery/table.py:1727: UserWarning: BigQuery Storage module not found, fetch data with the REST endpoint instead.
  warnings.warn(

       x_coordinate  y_coordinate       latitude      longitude
count  1.706100e+05  1.706100e+05  170610.000000  170610.000000
mean   1.164738e+06  1.886045e+06      41.842900     -87.670987
std    1.623515e+04  3.144288e+04       0.086473       0.059091
min    1.092706e+06  1.813910e+06      41.644608     -87.934273
25%    1.153207e+06  1.859232e+06      41.769068     -87.712775
50%    1.166264e+06  1.891446e+06      41.857680     -87.665305
75%    1.176406e+06  1.909501e+06      41.907381     -87.628069
max    1.205119e+06  1.951532e+06      42.022641     -87.524532

# Keep going

You've looked at the schema, but you haven't yet done anything exciting with the data itself. Things get more interesting when you get to the data, so keep going to **[write your first SQL query](https://www.kaggle.com/dansbecker/select-from-where).**

---




*Have questions or comments? Visit the [course discussion forum](https://www.kaggle.com/learn/intro-to-sql/discussion) to chat with other learners.*